global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nodejs-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"

